// #22: centralized, versioned storage schema
export const STORAGE_SCHEMA_VERSION = 1;
export const STORAGE_VERSION_KEY = "APP_SCHEMA_VERSION";

export const LOCAL_STORAGE_KEYS = {
  FAVORITE_POSITIONS_KEY: "FAVORITE_POSITIONS",
  HIDE_FAVORITES_SECTION_KEY: "HIDE_FAVORITES_SECTION_KEY",
  CUSTOM_TAGS_KEY: "CUSTOM_TAGS",
} as const;
